// convpng v7.0
// this file contains all the graphics sources for easy inclusion in a project
#ifndef __PKMNSD4__
#define __PKMNSD4__
#include <stdint.h>

#include <stdbool.h>

#define PKMNSD4_num 31

extern uint8_t *PKMNSD4[31];
#define player00_width 16
#define player00_height 20
#define player00_compressed ((gfx_sprite_t*)PKMNSD4[0])
#define player01_width 16
#define player01_height 20
#define player01_compressed ((gfx_sprite_t*)PKMNSD4[1])
#define player02_width 16
#define player02_height 20
#define player02_compressed ((gfx_sprite_t*)PKMNSD4[2])
#define player03_width 16
#define player03_height 20
#define player03_compressed ((gfx_sprite_t*)PKMNSD4[3])
#define player04_width 16
#define player04_height 20
#define player04_compressed ((gfx_sprite_t*)PKMNSD4[4])
#define player05_width 16
#define player05_height 20
#define player05_compressed ((gfx_sprite_t*)PKMNSD4[5])
#define player06_width 16
#define player06_height 20
#define player06_compressed ((gfx_sprite_t*)PKMNSD4[6])
#define player07_width 16
#define player07_height 20
#define player07_compressed ((gfx_sprite_t*)PKMNSD4[7])
#define player08_width 16
#define player08_height 20
#define player08_compressed ((gfx_sprite_t*)PKMNSD4[8])
#define player09_width 16
#define player09_height 20
#define player09_compressed ((gfx_sprite_t*)PKMNSD4[9])
#define player10_width 16
#define player10_height 20
#define player10_compressed ((gfx_sprite_t*)PKMNSD4[10])
#define player11_width 16
#define player11_height 20
#define player11_compressed ((gfx_sprite_t*)PKMNSD4[11])
#define player12_width 22
#define player12_height 26
#define player12_compressed ((gfx_sprite_t*)PKMNSD4[12])
#define player13_width 22
#define player13_height 26
#define player13_compressed ((gfx_sprite_t*)PKMNSD4[13])
#define player14_width 22
#define player14_height 26
#define player14_compressed ((gfx_sprite_t*)PKMNSD4[14])
#define player15_width 22
#define player15_height 26
#define player15_compressed ((gfx_sprite_t*)PKMNSD4[15])
#define player16_width 20
#define player16_height 26
#define player16_compressed ((gfx_sprite_t*)PKMNSD4[16])
#define player17_width 22
#define player17_height 26
#define player17_compressed ((gfx_sprite_t*)PKMNSD4[17])
#define player18_width 20
#define player18_height 26
#define player18_compressed ((gfx_sprite_t*)PKMNSD4[18])
#define player19_width 22
#define player19_height 26
#define player19_compressed ((gfx_sprite_t*)PKMNSD4[19])
#define enemy00_width 16
#define enemy00_height 20
#define enemy00_compressed ((gfx_sprite_t*)PKMNSD4[20])
#define enemy01_width 16
#define enemy01_height 20
#define enemy01_compressed ((gfx_sprite_t*)PKMNSD4[21])
#define enemy02_width 16
#define enemy02_height 20
#define enemy02_compressed ((gfx_sprite_t*)PKMNSD4[22])
#define enemy03_width 16
#define enemy03_height 20
#define enemy03_compressed ((gfx_sprite_t*)PKMNSD4[23])
#define maptextbox1_width 160
#define maptextbox1_height 64
#define maptextbox1_compressed ((gfx_sprite_t*)PKMNSD4[24])
#define maptextbox2_width 160
#define maptextbox2_height 64
#define maptextbox2_compressed ((gfx_sprite_t*)PKMNSD4[25])
#define pausemenu_width 112
#define pausemenu_height 96
#define pausemenu_compressed ((gfx_sprite_t*)PKMNSD4[26])
#define pokeball_width 48
#define pokeball_height 16
#define pokeball_compressed ((gfx_sprite_t*)PKMNSD4[27])
#define pokeball_tiles_num 3
extern uint8_t *pokeball_tiles_compressed[3];
#define pokeball_tile_0_compressed ((gfx_sprite_t*)pokeball_tiles_compressed[0])
#define pokeball_tile_1_compressed ((gfx_sprite_t*)pokeball_tiles_compressed[1])
#define pokeball_tile_2_compressed ((gfx_sprite_t*)pokeball_tiles_compressed[2])
#define outdoortileset_width 256
#define outdoortileset_height 128
#define outdoortileset_compressed ((gfx_sprite_t*)PKMNSD4[28])
#define outdoortileset_tiles_num 128
extern uint8_t *outdoortileset_tiles_compressed[128];
#define outdoortileset_tile_0_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[0])
#define outdoortileset_tile_1_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[1])
#define outdoortileset_tile_2_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[2])
#define outdoortileset_tile_3_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[3])
#define outdoortileset_tile_4_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[4])
#define outdoortileset_tile_5_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[5])
#define outdoortileset_tile_6_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[6])
#define outdoortileset_tile_7_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[7])
#define outdoortileset_tile_8_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[8])
#define outdoortileset_tile_9_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[9])
#define outdoortileset_tile_10_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[10])
#define outdoortileset_tile_11_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[11])
#define outdoortileset_tile_12_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[12])
#define outdoortileset_tile_13_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[13])
#define outdoortileset_tile_14_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[14])
#define outdoortileset_tile_15_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[15])
#define outdoortileset_tile_16_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[16])
#define outdoortileset_tile_17_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[17])
#define outdoortileset_tile_18_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[18])
#define outdoortileset_tile_19_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[19])
#define outdoortileset_tile_20_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[20])
#define outdoortileset_tile_21_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[21])
#define outdoortileset_tile_22_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[22])
#define outdoortileset_tile_23_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[23])
#define outdoortileset_tile_24_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[24])
#define outdoortileset_tile_25_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[25])
#define outdoortileset_tile_26_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[26])
#define outdoortileset_tile_27_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[27])
#define outdoortileset_tile_28_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[28])
#define outdoortileset_tile_29_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[29])
#define outdoortileset_tile_30_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[30])
#define outdoortileset_tile_31_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[31])
#define outdoortileset_tile_32_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[32])
#define outdoortileset_tile_33_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[33])
#define outdoortileset_tile_34_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[34])
#define outdoortileset_tile_35_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[35])
#define outdoortileset_tile_36_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[36])
#define outdoortileset_tile_37_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[37])
#define outdoortileset_tile_38_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[38])
#define outdoortileset_tile_39_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[39])
#define outdoortileset_tile_40_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[40])
#define outdoortileset_tile_41_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[41])
#define outdoortileset_tile_42_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[42])
#define outdoortileset_tile_43_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[43])
#define outdoortileset_tile_44_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[44])
#define outdoortileset_tile_45_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[45])
#define outdoortileset_tile_46_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[46])
#define outdoortileset_tile_47_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[47])
#define outdoortileset_tile_48_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[48])
#define outdoortileset_tile_49_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[49])
#define outdoortileset_tile_50_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[50])
#define outdoortileset_tile_51_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[51])
#define outdoortileset_tile_52_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[52])
#define outdoortileset_tile_53_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[53])
#define outdoortileset_tile_54_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[54])
#define outdoortileset_tile_55_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[55])
#define outdoortileset_tile_56_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[56])
#define outdoortileset_tile_57_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[57])
#define outdoortileset_tile_58_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[58])
#define outdoortileset_tile_59_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[59])
#define outdoortileset_tile_60_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[60])
#define outdoortileset_tile_61_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[61])
#define outdoortileset_tile_62_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[62])
#define outdoortileset_tile_63_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[63])
#define outdoortileset_tile_64_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[64])
#define outdoortileset_tile_65_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[65])
#define outdoortileset_tile_66_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[66])
#define outdoortileset_tile_67_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[67])
#define outdoortileset_tile_68_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[68])
#define outdoortileset_tile_69_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[69])
#define outdoortileset_tile_70_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[70])
#define outdoortileset_tile_71_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[71])
#define outdoortileset_tile_72_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[72])
#define outdoortileset_tile_73_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[73])
#define outdoortileset_tile_74_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[74])
#define outdoortileset_tile_75_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[75])
#define outdoortileset_tile_76_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[76])
#define outdoortileset_tile_77_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[77])
#define outdoortileset_tile_78_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[78])
#define outdoortileset_tile_79_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[79])
#define outdoortileset_tile_80_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[80])
#define outdoortileset_tile_81_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[81])
#define outdoortileset_tile_82_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[82])
#define outdoortileset_tile_83_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[83])
#define outdoortileset_tile_84_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[84])
#define outdoortileset_tile_85_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[85])
#define outdoortileset_tile_86_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[86])
#define outdoortileset_tile_87_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[87])
#define outdoortileset_tile_88_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[88])
#define outdoortileset_tile_89_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[89])
#define outdoortileset_tile_90_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[90])
#define outdoortileset_tile_91_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[91])
#define outdoortileset_tile_92_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[92])
#define outdoortileset_tile_93_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[93])
#define outdoortileset_tile_94_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[94])
#define outdoortileset_tile_95_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[95])
#define outdoortileset_tile_96_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[96])
#define outdoortileset_tile_97_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[97])
#define outdoortileset_tile_98_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[98])
#define outdoortileset_tile_99_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[99])
#define outdoortileset_tile_100_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[100])
#define outdoortileset_tile_101_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[101])
#define outdoortileset_tile_102_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[102])
#define outdoortileset_tile_103_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[103])
#define outdoortileset_tile_104_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[104])
#define outdoortileset_tile_105_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[105])
#define outdoortileset_tile_106_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[106])
#define outdoortileset_tile_107_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[107])
#define outdoortileset_tile_108_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[108])
#define outdoortileset_tile_109_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[109])
#define outdoortileset_tile_110_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[110])
#define outdoortileset_tile_111_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[111])
#define outdoortileset_tile_112_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[112])
#define outdoortileset_tile_113_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[113])
#define outdoortileset_tile_114_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[114])
#define outdoortileset_tile_115_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[115])
#define outdoortileset_tile_116_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[116])
#define outdoortileset_tile_117_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[117])
#define outdoortileset_tile_118_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[118])
#define outdoortileset_tile_119_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[119])
#define outdoortileset_tile_120_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[120])
#define outdoortileset_tile_121_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[121])
#define outdoortileset_tile_122_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[122])
#define outdoortileset_tile_123_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[123])
#define outdoortileset_tile_124_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[124])
#define outdoortileset_tile_125_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[125])
#define outdoortileset_tile_126_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[126])
#define outdoortileset_tile_127_compressed ((gfx_sprite_t*)outdoortileset_tiles_compressed[127])
#define indoortileset_width 256
#define indoortileset_height 128
#define indoortileset_compressed ((gfx_sprite_t*)PKMNSD4[29])
#define indoortileset_tiles_num 128
extern uint8_t *indoortileset_tiles_compressed[128];
#define indoortileset_tile_0_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[0])
#define indoortileset_tile_1_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[1])
#define indoortileset_tile_2_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[2])
#define indoortileset_tile_3_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[3])
#define indoortileset_tile_4_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[4])
#define indoortileset_tile_5_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[5])
#define indoortileset_tile_6_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[6])
#define indoortileset_tile_7_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[7])
#define indoortileset_tile_8_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[8])
#define indoortileset_tile_9_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[9])
#define indoortileset_tile_10_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[10])
#define indoortileset_tile_11_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[11])
#define indoortileset_tile_12_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[12])
#define indoortileset_tile_13_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[13])
#define indoortileset_tile_14_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[14])
#define indoortileset_tile_15_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[15])
#define indoortileset_tile_16_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[16])
#define indoortileset_tile_17_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[17])
#define indoortileset_tile_18_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[18])
#define indoortileset_tile_19_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[19])
#define indoortileset_tile_20_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[20])
#define indoortileset_tile_21_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[21])
#define indoortileset_tile_22_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[22])
#define indoortileset_tile_23_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[23])
#define indoortileset_tile_24_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[24])
#define indoortileset_tile_25_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[25])
#define indoortileset_tile_26_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[26])
#define indoortileset_tile_27_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[27])
#define indoortileset_tile_28_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[28])
#define indoortileset_tile_29_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[29])
#define indoortileset_tile_30_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[30])
#define indoortileset_tile_31_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[31])
#define indoortileset_tile_32_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[32])
#define indoortileset_tile_33_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[33])
#define indoortileset_tile_34_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[34])
#define indoortileset_tile_35_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[35])
#define indoortileset_tile_36_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[36])
#define indoortileset_tile_37_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[37])
#define indoortileset_tile_38_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[38])
#define indoortileset_tile_39_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[39])
#define indoortileset_tile_40_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[40])
#define indoortileset_tile_41_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[41])
#define indoortileset_tile_42_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[42])
#define indoortileset_tile_43_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[43])
#define indoortileset_tile_44_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[44])
#define indoortileset_tile_45_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[45])
#define indoortileset_tile_46_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[46])
#define indoortileset_tile_47_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[47])
#define indoortileset_tile_48_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[48])
#define indoortileset_tile_49_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[49])
#define indoortileset_tile_50_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[50])
#define indoortileset_tile_51_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[51])
#define indoortileset_tile_52_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[52])
#define indoortileset_tile_53_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[53])
#define indoortileset_tile_54_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[54])
#define indoortileset_tile_55_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[55])
#define indoortileset_tile_56_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[56])
#define indoortileset_tile_57_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[57])
#define indoortileset_tile_58_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[58])
#define indoortileset_tile_59_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[59])
#define indoortileset_tile_60_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[60])
#define indoortileset_tile_61_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[61])
#define indoortileset_tile_62_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[62])
#define indoortileset_tile_63_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[63])
#define indoortileset_tile_64_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[64])
#define indoortileset_tile_65_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[65])
#define indoortileset_tile_66_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[66])
#define indoortileset_tile_67_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[67])
#define indoortileset_tile_68_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[68])
#define indoortileset_tile_69_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[69])
#define indoortileset_tile_70_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[70])
#define indoortileset_tile_71_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[71])
#define indoortileset_tile_72_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[72])
#define indoortileset_tile_73_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[73])
#define indoortileset_tile_74_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[74])
#define indoortileset_tile_75_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[75])
#define indoortileset_tile_76_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[76])
#define indoortileset_tile_77_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[77])
#define indoortileset_tile_78_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[78])
#define indoortileset_tile_79_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[79])
#define indoortileset_tile_80_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[80])
#define indoortileset_tile_81_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[81])
#define indoortileset_tile_82_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[82])
#define indoortileset_tile_83_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[83])
#define indoortileset_tile_84_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[84])
#define indoortileset_tile_85_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[85])
#define indoortileset_tile_86_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[86])
#define indoortileset_tile_87_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[87])
#define indoortileset_tile_88_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[88])
#define indoortileset_tile_89_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[89])
#define indoortileset_tile_90_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[90])
#define indoortileset_tile_91_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[91])
#define indoortileset_tile_92_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[92])
#define indoortileset_tile_93_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[93])
#define indoortileset_tile_94_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[94])
#define indoortileset_tile_95_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[95])
#define indoortileset_tile_96_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[96])
#define indoortileset_tile_97_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[97])
#define indoortileset_tile_98_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[98])
#define indoortileset_tile_99_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[99])
#define indoortileset_tile_100_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[100])
#define indoortileset_tile_101_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[101])
#define indoortileset_tile_102_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[102])
#define indoortileset_tile_103_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[103])
#define indoortileset_tile_104_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[104])
#define indoortileset_tile_105_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[105])
#define indoortileset_tile_106_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[106])
#define indoortileset_tile_107_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[107])
#define indoortileset_tile_108_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[108])
#define indoortileset_tile_109_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[109])
#define indoortileset_tile_110_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[110])
#define indoortileset_tile_111_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[111])
#define indoortileset_tile_112_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[112])
#define indoortileset_tile_113_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[113])
#define indoortileset_tile_114_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[114])
#define indoortileset_tile_115_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[115])
#define indoortileset_tile_116_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[116])
#define indoortileset_tile_117_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[117])
#define indoortileset_tile_118_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[118])
#define indoortileset_tile_119_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[119])
#define indoortileset_tile_120_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[120])
#define indoortileset_tile_121_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[121])
#define indoortileset_tile_122_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[122])
#define indoortileset_tile_123_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[123])
#define indoortileset_tile_124_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[124])
#define indoortileset_tile_125_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[125])
#define indoortileset_tile_126_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[126])
#define indoortileset_tile_127_compressed ((gfx_sprite_t*)indoortileset_tiles_compressed[127])
#define sizeof_map_gfx_pal 460
#define map_gfx_pal ((uint16_t*)PKMNSD4[30])
bool PKMNSD4_init(void);

#endif
